# Generated by Django 6.0.3 on 2026-04-07 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_code', models.CharField(max_length=50)),
                ('company_name', models.CharField(max_length=100)),
                ('erp_server', models.CharField(max_length=100)),
                ('erp_database', models.CharField(max_length=100)),
                ('erp_user', models.CharField(max_length=100)),
                ('erp_password', models.CharField(max_length=100)),
                ('erp_port', models.IntegerField()),
                ('status', models.BooleanField(default=True)),
            ],
        ),
    ]
