# Generated by Django 5.2.6 on 2026-06-27 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_tenant_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRight',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('company_code', models.CharField(db_index=True, max_length=50)),
                ('user_id', models.IntegerField(db_index=True)),
                ('form_key', models.CharField(max_length=64)),
                ('has_access', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'usersrights',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TenantApproval',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tenantid', models.IntegerField(db_column='tenantid')),
                ('companycode', models.CharField(db_column='Companycode', max_length=50)),
                ('formname', models.CharField(db_column='formname', max_length=50)),
                ('transactionno', models.CharField(db_column='Transactionno', max_length=100)),
                ('transactiondate', models.DateField(blank=True, db_column='Transactiondate', null=True)),
                ('transactiontype', models.CharField(blank=True, db_column='Transactiontype', max_length=100, null=True)),
                ('approvedby', models.CharField(db_column='approvedby', max_length=100)),
                ('datetime', models.DateTimeField(db_column='datetime')),
            ],
            options={
                'db_table': 'tenants_approvals',
            },
        ),
        migrations.AlterModelTable(
            name='tenant',
            table='tenants',
        ),
    ]
